version: '3'
services:
  frontend:
    image: 1cf9db8/listadecomprasapp_frontend
    ports:
      - "80:80"

  backend:
    image: 1cf9db8/listadecomprasapp_backend
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
