FROM node:20.13.1

WORKDIR /app

COPY bun.lockb package.json ./

RUN npm install -g bun

RUN bun add serve

RUN bun install

COPY . .

RUN bun run build

EXPOSE 80

CMD ["npx", "serve", "-s", "dist/spa", "-l", "80"]
